sindrig/spoppy

spoppy/players.py
If shuffle is set when loading playlist and user does not specify whether he want's shuffle or not, shuffle the playlist.
This closes #1 
Also simplify loading+shuffling of playlist.
=> Maintain shuffle when selecting songs

spoppy/menus.py, spoppy/players.py
=> Don't fail when trying to play empty playlist

spoppy/menus.py, spoppy/navigation.py, spoppy/players.py
Only happens if we are currently playing something
This closes #15
=> Add song to queue or replace when song selected

requirements.txt, spoppy/lifecycle.py, spoppy/menus.py, spoppy/navigation.py, spoppy/search.py, spoppy/spotify_appkey.key
Also add the spotify appkey (i'm sure it should have been there already)
This closes #14
=> Add search capabilities, using the web api.

spoppy.py, spoppy/lifecycle.py, spoppy/menus.py, spoppy/navigation.py
=> Fix hangin when quitting

spoppy/menus.py, spoppy/navigation.py
=> Allow pagination using the arrow keys

spoppy/menus.py, spoppy/players.py
When playing in player and user is in menu, check for end_of_track after interrupt.
This fixes #43
=> Continue playing in menu

spoppy/players.py
=> Set playlist as none when we change the playlist

spoppy/players.py
=> Add option to remove songs from queue

spoppy/players.py
The user gets returned to his previous screen and the player gets unloaded
Also fixed some minor issues with the player
This closes #29
=> Add option to stop and clear the player

spoppy/menus.py, spoppy/players.py
Also fix issue with formatting when shuffling
This closes #47
=> Add whole playlist to queue

spoppy/search.py
=> Handle no internet connection in search

.gitignore, README.rst, requirements.txt, setup.py, spoppy/__init__.py, spoppy/dbus_listener.py, spoppy/navigation.py, spoppy/players.py, spoppy/terminal.py, spoppy/util.py, tests/test_menus.py, tests/test_players.py, tests/utils.py
=> Py27 support

spoppy/menus.py
=> Fix error when shuffling in search albums

spoppy/lifecycle.py, spoppy/players.py
This fixes #105
This kind of fixes #56
=> Pause if we are disconnected

spoppy/search.py
=> this closes #113, searching for empty string

spoppy/__init__.py, spoppy/menus.py, spoppy/radio.py
See #127 for more information. This will be fixed with beer later. @gunnardag
=> Show error message when we get HTTP 401 from spotify

spoppy/__init__.py, spoppy/players.py
=> Bugfix: uppercase in player must work

spoppy/__init__.py, spoppy/menus.py, spoppy/players.py, spoppy/util.py, tests/test_players.py
=> Add song temporary to queue. Song is removed once it's finished.

spoppy/__init__.py, spoppy/connectivity.py
This is for issue #134 - not sure if it fits the bill or not - but it sort of does what it says on the tin.
// Mike
=> Added rudimentary internet connectivity check.

spoppy/players.py, tests/test_players.py
=> Restart song if >5 secs played

spoppy/lifecycle.py, spoppy/loaders/loader.py, spoppy/navigation.py, spoppy/radio.py, spoppy/spotipy_wrapper.py
=> Refresh spotipy token

spoppy/__init__.py, spoppy/loaders/loader.py, spoppy/menus.py, spoppy/navigation.py, spoppy/radio.py, spoppy/spotipy_wrapper.py
=> Fix web api login for users that have not authenticated.

spoppy/__init__.py, spoppy/terminal.py
=> Fix terminal size in python 2.x

spoppy/__init__.py, spoppy/menus.py
=> Remove option to shuffle play playlist search

requirements.txt, spoppy/__init__.py, spoppy/lifecycle.py, spoppy/loaders/playlists.py, spoppy/menus.py, spoppy/navigation.py, spoppy/players.py, tests/test_menus.py
Fix error when fetching user playlists (possibly using wrong username)
Fix error when saving playlists (use web api)
Fix error when moving songs
=> Update spotipy. Bugfixes.
